import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { LeftSide } from "../components/LeftSide";
import { Post } from "../components/Post/Post";

const Home: NextPage = () => {
  return (
    <>
      <div className="container">
        <Head>
          <title>react-journal</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="static/logo.svg" />

          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />

          <link
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
            rel="stylesheet"
          />
        </Head>
      </div>
      <Header />

      <LeftSide />
      <Post />
      <div className="rightSide"></div>
    </>
  );
};

export default Home;
